services:
  niffler-all-db:
    extends:
      file: infra.yml
      service: niffler-all-db
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - niffler-network

  zookeeper:
    extends:
      file: infra.yml
      service: zookeeper
    networks:
      - niffler-network

  kafka:
    extends:
      file: infra.yml
      service: kafka
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - niffler-network

  auth.niffler.dc:
    container_name: auth.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-auth:latest
    ports:
      - "9000:9000"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=512m -XX:MaxHeapSize=768m
    healthcheck:
      test: "wget --spider http://localhost:9000/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - niffler-network

  currency.niffler.dc:
    container_name: currency.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-currency:latest
    ports:
      - "8091:8091"
      - "8092:8092"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=384m -XX:MaxHeapSize=512m
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network

  gateway.niffler.dc:
    container_name: gateway.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-gateway:latest
    ports:
      - "8090:8090"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=384m -XX:MaxHeapSize=512m
    healthcheck:
      test: "wget --spider http://localhost:8090/actuator/health || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    depends_on:
      auth.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network

  spend.niffler.dc:
    container_name: spend.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-spend:latest
    ports:
      - "8093:8093"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=384m -XX:MaxHeapSize=512m
    restart: always
    depends_on:
      niffler-all-db:
        condition: service_healthy
    networks:
      - niffler-network

  userdata.niffler.dc:
    container_name: userdata.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-userdata:latest
    ports:
      - "8089:8089"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:InitialHeapSize=384m -XX:MaxHeapSize=512m
    restart: always
    depends_on:
      auth.niffler.dc:
        condition: service_healthy
    networks:
      - niffler-network

  frontend.niffler.dc:
    container_name: frontend.niffler.dc
    image: ${REGISTRY:-qaguru}/niffler-ng-client:latest
    ports:
      - "80:80"
    depends_on:
      gateway.niffler.dc:
        condition: service_started
    networks:
      - niffler-network

networks:
  niffler-network:
    driver: bridge
