services:
  niffler-all-db:
    container_name: niffler-all-db
    image: postgres:15.1
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      TZ: ${TIMEZONE:-UTC}
    volumes:
      - ./postgres/script:/docker-entrypoint-initdb.d
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "max_prepared_transactions=100" ]

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.3.2
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    depends_on:
      zookeeper:
        condition: service_started
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1