version: '3'

dotenv: ['.env']

tasks:
  infra:up:
    desc: Start infrastructure services - postgres, kafka, zookeeper
    cmds:
      - docker-compose -f infra.yml up -d

  infra:down:
    desc: Shutdown infrastructure services - postgres, kafka, zookeeper
    cmds:
      - docker-compose -f infra.yml down
